#!/usr/bin/env python
# Memir is GPL3 program

import gtk, gobject, pygtk, locale

class mygui:
    def on_window1_destroy(self, widget, data=None):
        gtk.main_quit()

    def quit_btn_clicked_cb(self, widget, data=None):
        gtk.main_quit()
        
    def showway_btn_clicked_cb(self, widget, data=None):
        for code in self.encodings:
            for code2 in self.encodings:
                try:
                    if self.result.get_text() == self.input.get_text().encode(code).decode(code2):
                        self.combo_source.set_active(self.encodings.index(code))
                        self.combo_output.set_active(self.encodings.index(code2))
                except:
                    pass

    def mk_source_clicked_cb(self, widget, data=None):
        self.input.set_text(self.result.get_text())
        
    def input_changed(self, widget, data=None):
        self.convert()
        
    def result_changed(self, widget, data=None):
        self.output = self.encodings[widget.get_active()]
        self.convert()

    def source_changed(self, widget, data=None):
        self.source = self.encodings[widget.get_active()]
        self.convert()
        
    def convert(self):
        try:
            self.result.set_text(self.input.get_text().encode(self.source).decode(self.output))
        except:
            self.result.set_text("Can't encode "+self.input.get_text() + " from "+self.source+" to "+self.output)

    def __init__(self):
        builder = gtk.Builder()
        builder.add_from_file("memir.glade")
        self.window = builder.get_object("memir")
        self.combo_source = builder.get_object("from_encoding_combo")
        self.combo_output = builder.get_object("to_encoding_combo")
        self.result = builder.get_object("result_output")
        self.trace_btn = builder.get_object("showway_btn")
        self.input = builder.get_object("source_input")
        self.model = gtk.ListStore(gobject.TYPE_STRING)
        cell = gtk.CellRendererText()
        self.encodings = []
        for code in locale.encodings.aliases.aliases:
            self.encodings.append(locale.encodings.aliases.aliases[code])
        self.encodings = list(set(self.encodings))
        self.encodings.sort()
        for code in self.encodings:
            self.model.append([code])
        self.source = self.encodings[0]
        self.output = self.encodings[0]
        for w in [self.combo_source, self.combo_output]:            
            w.set_model(self.model)
            w.set_active(0)
            w.pack_start(cell, True) 
            w.add_attribute(cell, 'text', 0)
        builder.connect_signals(self)

if __name__ == "__main__":
        gui = mygui()
        gui.window.show()
        gtk.main()
